version: 2  # Keep only one version declaration

sources:
  - name: hr
    database: MYDB1  # Ensure correct case-sensitive database name
    schema: MYSCHEMA1
    tables:
      - name: employees
      - name: departments

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
    tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


  - name: it_department
    description: "IT Employees"
    columns:
      - name: employee_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

 - name: sales_department
    description: "sales Employees"
    columns:
      - name: employee_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null