version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:  # Corrected 'data_tests' to 'tests'
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: it_department  # FIXED: Now correctly indented under 'models'
    description: "IT Employees"
    columns:
      - name: employee_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
