<<<<<<< HEAD
version: 2
=======
version: 2  # Keep only one version declaration

sources:
  - name: hr
    database: MYDB1  # Ensure correct case-sensitive database name
    schema: MYSCHEMA1
    tables:
      - name: employees
      - name: departments
>>>>>>> a2c366e (Added new dbt models)

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
<<<<<<< HEAD
        tests:  # Corrected 'data_tests' to 'tests'
=======
        tests:
>>>>>>> a2c366e (Added new dbt models)
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

<<<<<<< HEAD
  - name: it_department  # FIXED: Now correctly indented under 'models'
=======
  - name: it_department
>>>>>>> a2c366e (Added new dbt models)
    description: "IT Employees"
    columns:
      - name: employee_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
