{{ config(
    materialized='table'
) }}
SELECT 
    O_ORDERDATE,
    SUM(O_TOTALPRICE) AS DAILY_SALES,
    SUM(SUM(O_TOTALPRICE)) OVER (ORDER BY O_ORDERDATE) AS CUMULATIVE_SALES
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
GROUP BY O_ORDERDATE
ORDER BY O_ORDERDATE